[build]
  publish = "dist"
  command = "npm run build:netlify"

[[redirects]]
  from = "/pitch-perfector2/*"
  to = "/pitch-perfector2/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
